### ISSUE TITLE
Link broken and application detected as unmaintened

### ISSUE THREAD

**Issue by wxgeo** [YunoHost-Apps/mytinytodo_ynh#50]
### Describe the bug

Link broken on Yunohost website for this application: [https://yunohost.org/en/app_mytinytodo](https://yunohost.org/en/app_mytinytodo
)

What's more, on the web interface of my yunohost installation, the diagnostic application now declares the application as unmaintened, though I didn't change anything in my yunohost installation, except routine package's update:

> Un problème a été détecté pour l'application myTinyTodo
> 
> Cette application est absente ou ne figure plus dans le catalogue d'applications de YunoHost. Vous devriez envisager de la désinstaller car elle ne recevra pas de mise à jour et pourrait compromettre l'intégrité et la sécurité de votre système.

When I run the diagnosis from the command line, I get an equivalent message:

```
 =================================
 Applications (apps)
 =================================
 
 [ERROR] An issue was found for app myTinyTodo
   - This application is not in YunoHost's application catalog. If it was in the past and got removed, you should consider uninstalling this app as it won't receive upgrade, and may compromise the integrity and security of your system.

```

### Context

- Hardware: Raspberry Pi 4 at home
- YunoHost version: 4.4.3 (stable).
- I have access to my server: through the webadmin, but I can reproduce the bug when accessing by ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

From CLI:

    ```sh
    sudo yunohost diagnosis run
    sudo yunohost diagnosis show --issues --human-readable
    ```

Or just got to  [https://yunohost.org/en/app_mytinytodo](https://yunohost.org/en/app_mytinytodo
).

### Expected behavior

The application seems to be still maintened (thank you so much for that, by the way, this is such a really nice and usefull application !).

### Logs

Don't seem relevant here (at least, url  [https://yunohost.org/en/app_mytinytodo](https://yunohost.org/en/app_mytinytodo
) shouldn't be broken, and this is clearly a problem on yunohost side !)

**Comment by alexAubin** [comment]
can you check what's the exact app id of that app on your install, using something such as : `sudo yunohost app list | grep -i todo`

**Comment by wxgeo** [comment]
```
    domain_path: pourcelot.noho.st/todo
    id: mytinytodo
    name: myTinyTodo
```
